In [20]:
import pandas as pd
from skimpy import skim

In [7]:
taxi_zone_lookup_df = pd.read_csv("data/taxi_zone_lookup.csv")
green_tripdata_df = pd.read_parquet("data/green_tripdata_2025-11.parquet")

In [25]:
display(taxi_zone_lookup_df.head())
display(taxi_zone_lookup_df.dtypes)
display(skim(taxi_zone_lookup))

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

LocationID      int64
Borough           str
Zone              str
service_zone      str
dtype: object

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 265    │ │ string      │ 3     │                                                          │
│ │ Number of columns │ 4      │ │ int64       │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃ column           ┃ NA   ┃ NA %    ┃ mean    ┃ sd       ┃ p0   ┃ p25   ┃ p50   ┃ p75   ┃ p100    ┃ hist     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━┩  │
│ │    LocationID    │    0 │       0 │     133 │    76.64 │    1 │    67 │   133 │   199 │     265 │  ██████  │  │
│ └──────────────────┴──────┴─────────┴─────────┴──────────┴──────┴───────┴───────┴───────┴─────────┴──────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │  Borough  │  0 │         0 │   EWR    │  Staten   │  Bronx   │  Unknown  │      7.6 │       1.1 │      285 │  │
│ │           │    │           │          │  Island   │          │           │          │           │          │  │
│ │   Zone    │  1 │ 0.3773584 │    NV    │ Governor' │ Allerton │ Yorkville │     15.8 │       2.1 │      550 │  │
│ │           │    │ 905660377 │          │     s     │ /Pelham  │   West    │          │           │          │  │
│ │           │    │         6 │          │ Island/El │ Gardens  │           │          │           │          │  │
│ │           │    │           │          │    lis    │          │           │          │           │          │  │
│ │           │    │           │          │ Island/Li │          │           │          │           │          │  │
│ │           │    │           │          │   berty   │          │           │          │           │          │  │
│ │           │    │           │          │  Island   │          │           │          │           │          │  │
│ │ service_z │  2 │ 0.7547169 │   EWR    │  Yellow   │ Airports │  Yellow   │     9.39 │         2 │      523 │  │
│ │    one    │    │ 811320755 │          │   Zone    │          │   Zone    │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

None

In [26]:
display(green_tripdata_df.head())
display(green_tripdata_df.dtypes)
display(skim(green_tripdata_df))

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 46912  │ │ float64     │ 15    │                                                          │
│ │ Number of columns │ 21     │ │ int64       │ 3     │                                                          │
│ └───────────────────┴────────┘ │ datetime64  │ 2     │                                                          │
│                                │ string      │ 1     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                    All null                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                                          ┃ NA                            ┃ NA %                     ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │                    ehail_fee                    │                         46912 │                      100 │  │
│ └─────────────────────────────────────────────────┴───────────────────────────────┴──────────────────────────┘  │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━━┓  │
│ ┃ column         ┃ NA   ┃ NA %           ┃ mean    ┃ sd     ┃ p0    ┃ p25   ┃ p50  ┃ p75   ┃ p100   ┃ hist   ┃  │
│ ┡━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━━┩  │
│ │    VendorID    │    0 │              0 │   2.241 │   1.17 │     1 │     2 │    2 │     2 │      6 │ ▁█   ▁ │  │
│ │   RatecodeID   │ 5569 │ 11.87116302864 │   1.245 │  1.063 │     1 │     1 │    1 │     1 │     99 │   █    │  │
│ │                │      │           9386 │         │        │       │       │      │       │        │        │  │
│ │  PULocationID  │    0 │              0 │   97.52 │  56.62 │     1 │    74 │   75 │   116 │    265 │ ▂█▂▁▁▁ │  │
│ │  DOLocationID  │    0 │              0 │   143.1 │  77.36 │     1 │    75 │  140 │   230 │    265 │ ▄▅▃▆▂█ │  │
│ │ passenger_coun │ 5569 │ 11.87116302864 │   1.291 │ 0.8979 │     0 │     1 │    1 │     1 │      9 │   █▁   │  │
│ │       t        │      │           9386 │         │        │       │       │      │       │        │        │  │
│ │ trip_distance  │    0 │              0 │   27.58 │   1387 │     0 │  1.28 │ 2.07 │  3.66 │ 172300 │   █    │  │
│ │  fare_amount   │    0 │              0 │   17.26 │  17.28 │  -150 │     9 │ 13.5 │  19.8 │    990 │   █▁   │  │
│ │     extra      │    0 │              0 │  0.7963 │  1.364 │  -2.5 │     0 │    0 │     1 │     10 │   █▂   │  │
│ │    mta_tax     │    0 │              0 │  0.5563 │ 0.3195 │  -0.5 │   0.5 │  0.5 │   0.5 │    1.5 │  ▁ █ ▁ │  │
│ │   tip_amount   │    0 │              0 │   2.629 │  3.411 │  -0.9 │     0 │ 2.08 │  3.92 │  122.1 │   █    │  │
│ │  tolls_amount  │    0 │              0 │  0.2734 │  1.513 │     0 │     0 │    0 │     0 │    108 │   █    │  │
│ │ improvement_su │    0 │              0 │  0.9306 │ 0.2332 │    -1 │     1 │    1 │     1 │      1 │    ▁ █ │  │
│ │    rcharge     │      │                │         │        │       │       │      │       │        │        │  │
│ │  total_amount  │    0 │              0 │   25.19 │  19.31 │  -151 │ 14.84 │ 20.3 │ 29.62 │    991 │   █▁   │  │
│ │  payment_type  │ 5569 │ 11.87116302864 │   1.246 │  0.461 │     1 │     1 │    1 │     1 │      5 │   █▂   │  │
│ │                │      │           9386 │         │        │       │       │      │       │        │        │  │
│ │   trip_type    │ 5570 │ 11.87329467939 │   1.055 │ 0.2288 │     1 │     1 │    1 │     1 │      2 │   █    │  │
│ │                │      │           9727 │         │        │       │       │      │       │        │        │  │
│ │ congestion_sur │ 5569 │ 11.87116302864 │  0.8841 │  1.285 │ -2.75 │     0 │    0 │  2.75 │   2.75 │    █ ▄ │  │
│ │     charge     │      │           9386 │         │        │       │       │      │       │        │        │  │
│ │ cbd_congestion │    0 │              0 │ 0.06489 │ 0.2111 │ -0.75 │     0 │    0 │     0 │   0.75 │    █ ▁ │  │
│ │      _fee      │      │                │         │        │       │       │      │       │        │        │  │
│ └────────────────┴──────┴────────────────┴─────────┴────────┴───────┴───────┴──────┴───────┴────────┴────────┘  │
│                                                    datetime                                                     │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃ column                     ┃ NA  ┃ NA %   ┃ first                   ┃ last                    ┃ frequency  ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │    lpep_pickup_datetime    │   0 │      0 │   2025-10-26 20:23:16   │   2025-12-01 20:29:00   │ None       │  │
│ │   lpep_dropoff_datetime    │   0 │      0 │   2025-10-26 20:31:18   │   2025-12-01 20:44:42   │ None       │  │
│ └────────────────────────────┴─────┴────────┴─────────────────────────┴─────────────────────────┴────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━┳━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┓  │
│ ┃             ┃      ┃             ┃          ┃         ┃     ┃     ┃ chars per   ┃ words per   ┃ total      ┃  │
│ ┃ column      ┃ NA   ┃ NA %        ┃ shortest ┃ longest ┃ min ┃ max ┃ row         ┃ row         ┃ words      ┃  │
│ ┡━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━╇━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━┩  │
│ │ store_and_f │ 5569 │ 11.87116302 │    N     │    N    │  N  │  Y  │           1 │        0.88 │      41343 │  │
│ │   wd_flag   │      │     8649386 │          │         │     │     │             │             │            │  │
│ └─────────────┴──────┴─────────────┴──────────┴─────────┴─────┴─────┴─────────────┴─────────────┴────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

None